// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Microsoft_UI_Designer_H
#define WINRT_Microsoft_UI_Designer_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260520.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260520.1"
#include "winrt/Microsoft.UI.h"
#include "winrt/impl/Microsoft.UI.2.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Microsoft.UI.Designer.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Microsoft_UI_Designer_IDesignerOutputHost<D>::WindowId() const
    {
        winrt::Microsoft::UI::WindowId value{};
        consume_general<winrt::Microsoft::UI::Designer::IDesignerOutputHost, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::UI::Designer::IDesignerOutputHost>::get_WindowId, put_abi(value));
        return value;
    }
    template <typename D> auto consume_Microsoft_UI_Designer_IDesignerOutputHostStatics<D>::CreateForWindowId(winrt::Windows::UI::Composition::Compositor const& compositor, winrt::Microsoft::UI::WindowId const& windowId) const
    {
        void* result{};
        consume_general<winrt::Microsoft::UI::Designer::IDesignerOutputHostStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::UI::Designer::IDesignerOutputHostStatics>::CreateForWindowId, *(void**)(&compositor), impl::bind_in(windowId), &result);
        return winrt::Microsoft::UI::Designer::DesignerOutputHost{ result, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::UI::Designer::IDesignerOutputHost> : produce_base<D, winrt::Microsoft::UI::Designer::IDesignerOutputHost>
    {
        std::int32_t __stdcall get_WindowId(struct struct_Microsoft_UI_WindowId* value) noexcept final try
        {
            zero_abi<winrt::Microsoft::UI::WindowId>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::UI::WindowId>(this->shim().WindowId());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::UI::Designer::IDesignerOutputHostStatics> : produce_base<D, winrt::Microsoft::UI::Designer::IDesignerOutputHostStatics>
    {
        std::int32_t __stdcall CreateForWindowId(void* compositor, struct struct_Microsoft_UI_WindowId windowId, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::UI::Designer::DesignerOutputHost>(this->shim().CreateForWindowId(*reinterpret_cast<winrt::Windows::UI::Composition::Compositor const*>(&compositor), *reinterpret_cast<winrt::Microsoft::UI::WindowId const*>(&windowId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Microsoft::UI::Designer
{
    inline auto DesignerOutputHost::CreateForWindowId(winrt::Windows::UI::Composition::Compositor const& compositor, winrt::Microsoft::UI::WindowId const& windowId)
    {
        return impl::call_factory<DesignerOutputHost, IDesignerOutputHostStatics>([&](IDesignerOutputHostStatics const& f) { return f.CreateForWindowId(compositor, windowId); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Microsoft::UI::Designer::IDesignerOutputHost> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::UI::Designer::IDesignerOutputHostStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::UI::Designer::DesignerOutputHost> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
