// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Microsoft_Windows_ImageCreationInternal_H
#define WINRT_Microsoft_Windows_ImageCreationInternal_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260520.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260520.1"
#include "winrt/impl/Microsoft.Windows.PrivateCommon.2.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Graphics.2.h"
#include "winrt/impl/Microsoft.Windows.ImageCreationInternal.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Microsoft_Windows_ImageCreationInternal_IImageGeneratorSession<D>::CreateImageFromOptions(winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const& options, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& outputImageBufferResource) const
    {
        void* result{};
        consume_general<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession>::CreateImageFromOptions, impl::bind_in(options), *(void**)(&outputImageBufferResource), &result);
        return winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_ImageCreationInternal_IImageGeneratorSession<D>::CreateImage(winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const& options, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& inputImageBufferResource, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& outputImageBufferResource) const
    {
        void* result{};
        consume_general<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession>::CreateImage, impl::bind_in(options), *(void**)(&inputImageBufferResource), *(void**)(&outputImageBufferResource), &result);
        return winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_ImageCreationInternal_IImageGeneratorSession<D>::MagicFill(winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const& options, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& inputImageBufferResource, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& inputMaskBufferResource, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& outputImageBufferResource) const
    {
        void* result{};
        consume_general<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession>::MagicFill, impl::bind_in(options), *(void**)(&inputImageBufferResource), *(void**)(&inputMaskBufferResource), *(void**)(&outputImageBufferResource), &result);
        return winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_ImageCreationInternal_IImageGeneratorSession<D>::GetMaximumInputOutputImageDimensions(winrt::Windows::Graphics::SizeInt32& inputImageDimensions, winrt::Windows::Graphics::SizeInt32& outputImageDimensions) const
    {
        consume_general<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession>::GetMaximumInputOutputImageDimensions, impl::bind_out(inputImageDimensions), impl::bind_out(outputImageDimensions));
    }
    template <typename D> auto consume_Microsoft_Windows_ImageCreationInternal_IImageGeneratorSession2<D>::GenerateColoringBookStyleImageFromTextPrompt(winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const& options, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& outputImageBufferResource) const
    {
        void* result{};
        consume_general<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession2, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession2>::GenerateColoringBookStyleImageFromTextPrompt, impl::bind_in(options), *(void**)(&outputImageBufferResource), &result);
        return winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_ImageCreationInternal_IImageGeneratorSession2<D>::GenerateRestyledImageFromImageBuffer(winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const& options, float colorPreservationFactor, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& inputImageBufferResource, winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const& outputImageBufferResource) const
    {
        void* result{};
        consume_general<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession2, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession2>::GenerateRestyledImageFromImageBuffer, impl::bind_in(options), colorPreservationFactor, *(void**)(&inputImageBufferResource), *(void**)(&outputImageBufferResource), &result);
        return winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_ImageCreationInternal_IImageGeneratorSessionResult<D>::Status() const
    {
        winrt::Microsoft::Windows::ImageCreationInternal::ImageGeneratorResponseStatusInternal value{};
        consume_general<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult>::get_Status, reinterpret_cast<std::int32_t*>(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_ImageCreationInternal_IImageGeneratorSessionResult<D>::ExtendedError() const
    {
        winrt::hresult value{};
        consume_general<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult>::get_ExtendedError, put_abi(value));
        return value;
    }
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession> : produce_base<D, winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession>
    {
        std::int32_t __stdcall CreateImageFromOptions(struct struct_Microsoft_Windows_ImageCreationInternal_ImageGenerationOptionsInternal options, void* outputImageBufferResource, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult>(this->shim().CreateImageFromOptions(*reinterpret_cast<winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const*>(&options), *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&outputImageBufferResource)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall CreateImage(struct struct_Microsoft_Windows_ImageCreationInternal_ImageGenerationOptionsInternal options, void* inputImageBufferResource, void* outputImageBufferResource, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult>(this->shim().CreateImage(*reinterpret_cast<winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const*>(&options), *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&inputImageBufferResource), *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&outputImageBufferResource)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall MagicFill(struct struct_Microsoft_Windows_ImageCreationInternal_ImageGenerationOptionsInternal options, void* inputImageBufferResource, void* inputMaskBufferResource, void* outputImageBufferResource, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult>(this->shim().MagicFill(*reinterpret_cast<winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const*>(&options), *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&inputImageBufferResource), *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&inputMaskBufferResource), *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&outputImageBufferResource)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetMaximumInputOutputImageDimensions(struct struct_Windows_Graphics_SizeInt32* inputImageDimensions, struct struct_Windows_Graphics_SizeInt32* outputImageDimensions) noexcept final try
        {
            zero_abi<winrt::Windows::Graphics::SizeInt32>(inputImageDimensions);
            zero_abi<winrt::Windows::Graphics::SizeInt32>(outputImageDimensions);
            typename D::abi_guard guard(this->shim());
            this->shim().GetMaximumInputOutputImageDimensions(*reinterpret_cast<winrt::Windows::Graphics::SizeInt32*>(inputImageDimensions), *reinterpret_cast<winrt::Windows::Graphics::SizeInt32*>(outputImageDimensions));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession2> : produce_base<D, winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession2>
    {
        std::int32_t __stdcall GenerateColoringBookStyleImageFromTextPrompt(struct struct_Microsoft_Windows_ImageCreationInternal_ImageGenerationOptionsInternal options, void* outputImageBufferResource, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult>(this->shim().GenerateColoringBookStyleImageFromTextPrompt(*reinterpret_cast<winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const*>(&options), *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&outputImageBufferResource)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GenerateRestyledImageFromImageBuffer(struct struct_Microsoft_Windows_ImageCreationInternal_ImageGenerationOptionsInternal options, float colorPreservationFactor, void* inputImageBufferResource, void* outputImageBufferResource, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult>(this->shim().GenerateRestyledImageFromImageBuffer(*reinterpret_cast<winrt::Microsoft::Windows::ImageCreationInternal::ImageGenerationOptionsInternal const*>(&options), colorPreservationFactor, *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&inputImageBufferResource), *reinterpret_cast<winrt::Microsoft::Windows::PrivateCommon::ImageBufferResource const*>(&outputImageBufferResource)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult> : produce_base<D, winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult>
    {
        std::int32_t __stdcall get_Status(std::int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::ImageCreationInternal::ImageGeneratorResponseStatusInternal>(this->shim().Status());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ExtendedError(winrt::hresult* value) noexcept final try
        {
            zero_abi<winrt::hresult>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::hresult>(this->shim().ExtendedError());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::Microsoft::Windows::ImageCreationInternal
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSession2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::ImageCreationInternal::IImageGeneratorSessionResult> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
