// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

#pragma once
#ifndef WINRT_Microsoft_Windows_Internal_AI_Generative_0_H
#define WINRT_Microsoft_Windows_Internal_AI_Generative_0_H
WINRT_EXPORT namespace winrt::Microsoft::Windows::AI::GenerativeInternal
{
    struct IImageDescriptionSession2;
    struct IImageDescriptionSessionResult;
    struct IImageLLMAdapterSession;
    struct ILanguageModelSession6;
    struct ILanguageModelSessionAdapter;
    struct ILanguageModelSessionContext;
    struct ILanguageModelSessionCore3;
}
WINRT_EXPORT namespace winrt::Microsoft::Windows::Internal::AI::Generative
{
    struct IImageDescriptionSessionResult;
    struct ILanguageModelAdapterWrapper;
    struct ILanguageModelContextWrapper;
    struct HCFLanguageModelSession;
    struct ImageDescriptionSession;
    struct ImageDescriptionSessionResult;
    struct ImageLLMAdapterSession;
    struct LanguageModelAdapterWrapper;
    struct LanguageModelContextWrapper;
    struct LanguageModelSession;
    struct SettingsModelSession;
    struct GenerativeInternalContract;
}
WINRT_EXPORT namespace winrt::impl
{
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::IImageDescriptionSessionResult>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelAdapterWrapper>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelContextWrapper>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::HCFLanguageModelSession>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::ImageDescriptionSession>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::ImageDescriptionSessionResult>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::ImageLLMAdapterSession>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelAdapterWrapper>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelContextWrapper>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelSession>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::AI::Generative::SettingsModelSession>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::HCFLanguageModelSession> = L"Microsoft.Windows.Internal.AI.Generative.HCFLanguageModelSession";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::ImageDescriptionSession> = L"Microsoft.Windows.Internal.AI.Generative.ImageDescriptionSession";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::ImageDescriptionSessionResult> = L"Microsoft.Windows.Internal.AI.Generative.ImageDescriptionSessionResult";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::ImageLLMAdapterSession> = L"Microsoft.Windows.Internal.AI.Generative.ImageLLMAdapterSession";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelAdapterWrapper> = L"Microsoft.Windows.Internal.AI.Generative.LanguageModelAdapterWrapper";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelContextWrapper> = L"Microsoft.Windows.Internal.AI.Generative.LanguageModelContextWrapper";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelSession> = L"Microsoft.Windows.Internal.AI.Generative.LanguageModelSession";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::SettingsModelSession> = L"Microsoft.Windows.Internal.AI.Generative.SettingsModelSession";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::IImageDescriptionSessionResult> = L"Microsoft.Windows.Internal.AI.Generative.IImageDescriptionSessionResult";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelAdapterWrapper> = L"Microsoft.Windows.Internal.AI.Generative.ILanguageModelAdapterWrapper";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelContextWrapper> = L"Microsoft.Windows.Internal.AI.Generative.ILanguageModelContextWrapper";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::AI::Generative::GenerativeInternalContract> = L"Microsoft.Windows.Internal.AI.Generative.GenerativeInternalContract";
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::Internal::AI::Generative::IImageDescriptionSessionResult>{ 0x939F98F7,0x85F3,0x57F5,{ 0xB7,0x92,0xE7,0x4C,0xDB,0x03,0xCE,0x8C } }; // 939F98F7-85F3-57F5-B792-E74CDB03CE8C
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelAdapterWrapper>{ 0x965AC54F,0xB31D,0x5D99,{ 0xB8,0x6B,0x92,0x38,0xF3,0x03,0x90,0xA8 } }; // 965AC54F-B31D-5D99-B86B-9238F30390A8
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelContextWrapper>{ 0x6A609059,0xBA51,0x5918,{ 0x80,0x8F,0x43,0x17,0x05,0x3F,0xEC,0x7A } }; // 6A609059-BA51-5918-808F-4317053FEC7A
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::AI::Generative::HCFLanguageModelSession>{ using type = winrt::Microsoft::Windows::AI::GenerativeInternal::ILanguageModelSessionCore3; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::AI::Generative::ImageDescriptionSession>{ using type = winrt::Microsoft::Windows::AI::GenerativeInternal::IImageDescriptionSession2; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::AI::Generative::ImageDescriptionSessionResult>{ using type = winrt::Microsoft::Windows::AI::GenerativeInternal::IImageDescriptionSessionResult; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::AI::Generative::ImageLLMAdapterSession>{ using type = winrt::Microsoft::Windows::AI::GenerativeInternal::IImageLLMAdapterSession; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelAdapterWrapper>{ using type = winrt::Microsoft::Windows::AI::GenerativeInternal::ILanguageModelSessionAdapter; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelContextWrapper>{ using type = winrt::Microsoft::Windows::AI::GenerativeInternal::ILanguageModelSessionContext; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::AI::Generative::LanguageModelSession>{ using type = winrt::Microsoft::Windows::AI::GenerativeInternal::ILanguageModelSession6; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::AI::Generative::SettingsModelSession>{ using type = winrt::Microsoft::Windows::AI::GenerativeInternal::ILanguageModelSession6; };
    template <> struct abi<winrt::Microsoft::Windows::Internal::AI::Generative::IImageDescriptionSessionResult>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelAdapterWrapper>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelContextWrapper>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_Microsoft_Windows_Internal_AI_Generative_IImageDescriptionSessionResult
    {
    };
    template <> struct consume<winrt::Microsoft::Windows::Internal::AI::Generative::IImageDescriptionSessionResult>
    {
        template <typename D> using type = consume_Microsoft_Windows_Internal_AI_Generative_IImageDescriptionSessionResult<D>;
    };
    template <typename D>
    struct consume_Microsoft_Windows_Internal_AI_Generative_ILanguageModelAdapterWrapper
    {
    };
    template <> struct consume<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelAdapterWrapper>
    {
        template <typename D> using type = consume_Microsoft_Windows_Internal_AI_Generative_ILanguageModelAdapterWrapper<D>;
    };
    template <typename D>
    struct consume_Microsoft_Windows_Internal_AI_Generative_ILanguageModelContextWrapper
    {
    };
    template <> struct consume<winrt::Microsoft::Windows::Internal::AI::Generative::ILanguageModelContextWrapper>
    {
        template <typename D> using type = consume_Microsoft_Windows_Internal_AI_Generative_ILanguageModelContextWrapper<D>;
    };
}
#endif
