// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Microsoft_UI_Input_Experimental_2_H
#define WINRT_Microsoft_UI_Input_Experimental_2_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Microsoft.UI.Input.Experimental.1.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Microsoft::UI::Input::Experimental
{
    struct WINRT_IMPL_EMPTY_BASES ExpInputSite : winrt::Microsoft::UI::Input::Experimental::IExpInputSite,
        impl::require<ExpInputSite, winrt::Windows::Foundation::IClosable>
    {
        ExpInputSite(std::nullptr_t) noexcept {}
        ExpInputSite(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Input::Experimental::IExpInputSite(ptr, take_ownership_from_abi) {}
    };
}
#endif
