// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260715.1

#pragma once
#ifndef WINRT_Microsoft_Graphics_ImagingInternal_ImageObjectRemover_1_H
#define WINRT_Microsoft_Graphics_ImagingInternal_ImageObjectRemover_1_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Microsoft.Graphics.ImagingInternal.ImageObjectRemover.0.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Microsoft::Graphics::ImagingInternal::ImageObjectRemover
{
    struct WINRT_IMPL_EMPTY_BASES IImageObjectRemoverSession :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IImageObjectRemoverSession>,
        impl::require<winrt::Microsoft::Graphics::ImagingInternal::ImageObjectRemover::IImageObjectRemoverSession, winrt::Windows::Foundation::IClosable>
    {
        IImageObjectRemoverSession(std::nullptr_t = nullptr) noexcept {}
        IImageObjectRemoverSession(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
