// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Microsoft_Windows_AI_Foundation_2_H
#define WINRT_Microsoft_Windows_AI_Foundation_2_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Microsoft.Windows.AI.Foundation.1.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Microsoft::Windows::AI::Foundation
{
    struct WINRT_IMPL_EMPTY_BASES EmbeddingVector : winrt::Microsoft::Windows::AI::Foundation::IEmbeddingVector
    {
        EmbeddingVector(std::nullptr_t) noexcept {}
        EmbeddingVector(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Windows::AI::Foundation::IEmbeddingVector(ptr, take_ownership_from_abi) {}
        EmbeddingVector(array_view<float const> data, winrt::guid const& vectorSpaceID);
    };
}
#endif
