// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Microsoft_Windows_BadgeNotifications_2_H
#define WINRT_Microsoft_Windows_BadgeNotifications_2_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Microsoft.Windows.BadgeNotifications.1.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Microsoft::Windows::BadgeNotifications
{
    struct WINRT_IMPL_EMPTY_BASES BadgeNotificationManager : winrt::Microsoft::Windows::BadgeNotifications::IBadgeNotificationManager
    {
        BadgeNotificationManager(std::nullptr_t) noexcept {}
        BadgeNotificationManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Windows::BadgeNotifications::IBadgeNotificationManager(ptr, take_ownership_from_abi) {}
        [[nodiscard]] static auto Current();
    };
}
#endif
