// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Microsoft_Windows_Security_AccessControl_H
#define WINRT_Microsoft_Windows_Security_AccessControl_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260520.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260520.1"
#include "winrt/impl/Microsoft.Windows.Security.AccessControl.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Microsoft_Windows_Security_AccessControl_ISecurityDescriptorHelpersStatics<D>::GetSddlForAppContainerNames(array_view<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const> accessRequests, param::hstring const& principalStringSid, std::uint32_t principalAccessMask) const
    {
        void* result{};
        consume_general<winrt::Microsoft::Windows::Security::AccessControl::ISecurityDescriptorHelpersStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::Security::AccessControl::ISecurityDescriptorHelpersStatics>::GetSddlForAppContainerNames, accessRequests.size(), get_abi(accessRequests), *(void**)(&principalStringSid), principalAccessMask, &result);
        return hstring{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Security_AccessControl_ISecurityDescriptorHelpersStatics<D>::GetSecurityDescriptorBytesFromAppContainerNames(array_view<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const> accessRequests, param::hstring const& principalStringSid, std::uint32_t principalAccessMask) const
    {
        std::uint32_t result_impl_size{};
        std::uint8_t* result{};
        consume_general<winrt::Microsoft::Windows::Security::AccessControl::ISecurityDescriptorHelpersStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Microsoft::Windows::Security::AccessControl::ISecurityDescriptorHelpersStatics>::GetSecurityDescriptorBytesFromAppContainerNames, accessRequests.size(), get_abi(accessRequests), *(void**)(&principalStringSid), principalAccessMask, &result_impl_size, &result);
        return com_array<std::uint8_t>{ result, result_impl_size, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Security::AccessControl::ISecurityDescriptorHelpersStatics> : produce_base<D, winrt::Microsoft::Windows::Security::AccessControl::ISecurityDescriptorHelpersStatics>
    {
        std::int32_t __stdcall GetSddlForAppContainerNames(std::uint32_t __accessRequestsSize, struct struct_Microsoft_Windows_Security_AccessControl_AppContainerNameAndAccess* accessRequests, void* principalStringSid, std::uint32_t principalAccessMask, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<hstring>(this->shim().GetSddlForAppContainerNames(array_view<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const>(reinterpret_cast<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const *>(accessRequests), reinterpret_cast<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const *>(accessRequests) + __accessRequestsSize), *reinterpret_cast<hstring const*>(&principalStringSid), principalAccessMask));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetSecurityDescriptorBytesFromAppContainerNames(std::uint32_t __accessRequestsSize, struct struct_Microsoft_Windows_Security_AccessControl_AppContainerNameAndAccess* accessRequests, void* principalStringSid, std::uint32_t principalAccessMask, std::uint32_t* __resultSize, std::uint8_t** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            std::tie(*__resultSize, *result) = detach_abi(this->shim().GetSecurityDescriptorBytesFromAppContainerNames(array_view<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const>(reinterpret_cast<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const *>(accessRequests), reinterpret_cast<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const *>(accessRequests) + __accessRequestsSize), *reinterpret_cast<hstring const*>(&principalStringSid), principalAccessMask));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Microsoft::Windows::Security::AccessControl
{
    inline auto SecurityDescriptorHelpers::GetSddlForAppContainerNames(array_view<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const> accessRequests, param::hstring const& principalStringSid, std::uint32_t principalAccessMask)
    {
        return impl::call_factory<SecurityDescriptorHelpers, ISecurityDescriptorHelpersStatics>([&](ISecurityDescriptorHelpersStatics const& f) { return f.GetSddlForAppContainerNames(accessRequests, principalStringSid, principalAccessMask); });
    }
    inline auto SecurityDescriptorHelpers::GetSecurityDescriptorBytesFromAppContainerNames(array_view<winrt::Microsoft::Windows::Security::AccessControl::AppContainerNameAndAccess const> accessRequests, param::hstring const& principalStringSid, std::uint32_t principalAccessMask)
    {
        return impl::call_factory<SecurityDescriptorHelpers, ISecurityDescriptorHelpersStatics>([&](ISecurityDescriptorHelpersStatics const& f) { return f.GetSecurityDescriptorBytesFromAppContainerNames(accessRequests, principalStringSid, principalAccessMask); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Microsoft::Windows::Security::AccessControl::ISecurityDescriptorHelpersStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Security::AccessControl::SecurityDescriptorHelpers> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
