// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

#pragma once
#ifndef WINRT_Microsoft_Windows_Internal_Vision_0_H
#define WINRT_Microsoft_Windows_Internal_Vision_0_H
WINRT_EXPORT namespace winrt::Microsoft::Windows::VisionInternal
{
    struct IRecognizedTablesInternal;
    struct IRecognizedTextInternal;
    struct IScreenRegionDetectorSession4;
    struct ITextRecognizerSession6;
}
WINRT_EXPORT namespace winrt::Microsoft::Windows::Internal::Vision
{
    struct RecognizedTablesInternal;
    struct RecognizedTextInternal;
    struct ScreenRegionDetectorSession;
    struct TextRecognizerSession;
    struct VisionTextRecognitionContract;
}
WINRT_EXPORT namespace winrt::impl
{
    template <> struct category<winrt::Microsoft::Windows::Internal::Vision::RecognizedTablesInternal>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::Vision::RecognizedTextInternal>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::Vision::ScreenRegionDetectorSession>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::Internal::Vision::TextRecognizerSession>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::Vision::RecognizedTablesInternal> = L"Microsoft.Windows.Internal.Vision.RecognizedTablesInternal";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::Vision::RecognizedTextInternal> = L"Microsoft.Windows.Internal.Vision.RecognizedTextInternal";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::Vision::ScreenRegionDetectorSession> = L"Microsoft.Windows.Internal.Vision.ScreenRegionDetectorSession";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::Vision::TextRecognizerSession> = L"Microsoft.Windows.Internal.Vision.TextRecognizerSession";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::Internal::Vision::VisionTextRecognitionContract> = L"Microsoft.Windows.Internal.Vision.VisionTextRecognitionContract";
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::Vision::RecognizedTablesInternal>{ using type = winrt::Microsoft::Windows::VisionInternal::IRecognizedTablesInternal; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::Vision::RecognizedTextInternal>{ using type = winrt::Microsoft::Windows::VisionInternal::IRecognizedTextInternal; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::Vision::ScreenRegionDetectorSession>{ using type = winrt::Microsoft::Windows::VisionInternal::IScreenRegionDetectorSession4; };
    template <> struct default_interface<winrt::Microsoft::Windows::Internal::Vision::TextRecognizerSession>{ using type = winrt::Microsoft::Windows::VisionInternal::ITextRecognizerSession6; };
}
#endif
