// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260818.1

#pragma once
#ifndef WINRT_Microsoft_UI_Xaml_XamlTypeInfo_0_H
#define WINRT_Microsoft_UI_Xaml_XamlTypeInfo_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::XamlTypeInfo
{
    struct IXamlControlsChartsXamlMetaDataProvider;
    struct IXamlControlsTabularXamlMetaDataProvider;
    struct IXamlControlsTabularXamlMetaDataProviderStatics;
    struct IXamlControlsXamlMetaDataProvider;
    struct IXamlControlsXamlMetaDataProviderStatics;
    struct XamlControlsChartsXamlMetaDataProvider;
    struct XamlControlsTabularXamlMetaDataProvider;
    struct XamlControlsXamlMetaDataProvider;
}
WINRT_EXPORT namespace winrt::impl
{
    template <> struct category<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsChartsXamlMetaDataProvider>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProvider>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProviderStatics>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsChartsXamlMetaDataProvider>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsTabularXamlMetaDataProvider>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsChartsXamlMetaDataProvider> = L"Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsChartsXamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsTabularXamlMetaDataProvider> = L"Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsTabularXamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider> = L"Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsChartsXamlMetaDataProvider> = L"Microsoft.UI.Xaml.XamlTypeInfo.IXamlControlsChartsXamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProvider> = L"Microsoft.UI.Xaml.XamlTypeInfo.IXamlControlsTabularXamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProviderStatics> = L"Microsoft.UI.Xaml.XamlTypeInfo.IXamlControlsTabularXamlMetaDataProviderStatics";
    template <> inline constexpr auto& name_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider> = L"Microsoft.UI.Xaml.XamlTypeInfo.IXamlControlsXamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics> = L"Microsoft.UI.Xaml.XamlTypeInfo.IXamlControlsXamlMetaDataProviderStatics";
    template <> inline constexpr guid guid_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsChartsXamlMetaDataProvider>{ 0xF2998F67,0xCCFC,0x5FCC,{ 0xB9,0x28,0x3A,0xD5,0xD3,0x96,0x4B,0x2B } }; // F2998F67-CCFC-5FCC-B928-3AD5D3964B2B
    template <> inline constexpr guid guid_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProvider>{ 0x870F3250,0x35C6,0x532F,{ 0x87,0x59,0x96,0x15,0xDF,0x97,0x84,0xE1 } }; // 870F3250-35C6-532F-8759-9615DF9784E1
    template <> inline constexpr guid guid_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProviderStatics>{ 0xF7322B83,0x40DF,0x5F33,{ 0xBB,0x0C,0x70,0xBF,0xAE,0xE8,0x1D,0x29 } }; // F7322B83-40DF-5F33-BB0C-70BFAEE81D29
    template <> inline constexpr guid guid_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>{ 0x17FA3F58,0x3472,0x5AA2,{ 0xA0,0xF8,0x1A,0xB8,0xA5,0x19,0x57,0x3D } }; // 17FA3F58-3472-5AA2-A0F8-1AB8A519573D
    template <> inline constexpr guid guid_v<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics>{ 0x2D7EB3FD,0xECDB,0x5084,{ 0xB7,0xE0,0x12,0xF9,0x59,0x83,0x81,0xEF } }; // 2D7EB3FD-ECDB-5084-B7E0-12F9598381EF
    template <> struct default_interface<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsChartsXamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsChartsXamlMetaDataProvider; };
    template <> struct default_interface<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsTabularXamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct default_interface<winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsChartsXamlMetaDataProvider>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProvider>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProviderStatics>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall Initialize() noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall Initialize() noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsChartsXamlMetaDataProvider
    {
    };
    template <> struct consume<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsChartsXamlMetaDataProvider>
    {
        template <typename D> using type = consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsChartsXamlMetaDataProvider<D>;
    };
    template <typename D>
    struct consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsTabularXamlMetaDataProvider
    {
    };
    template <> struct consume<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProvider>
    {
        template <typename D> using type = consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsTabularXamlMetaDataProvider<D>;
    };
    template <typename D>
    struct consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsTabularXamlMetaDataProviderStatics
    {
        auto Initialize() const;
    };
    template <> struct consume<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsTabularXamlMetaDataProviderStatics>
    {
        template <typename D> using type = consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsTabularXamlMetaDataProviderStatics<D>;
    };
    template <typename D>
    struct consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsXamlMetaDataProvider
    {
    };
    template <> struct consume<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>
    {
        template <typename D> using type = consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsXamlMetaDataProvider<D>;
    };
    template <typename D>
    struct consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsXamlMetaDataProviderStatics
    {
        auto Initialize() const;
    };
    template <> struct consume<winrt::Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics>
    {
        template <typename D> using type = consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsXamlMetaDataProviderStatics<D>;
    };
}
#endif
