// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Microsoft_UI_Input_Interop_1_H
#define WINRT_Microsoft_UI_Input_Interop_1_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Microsoft.UI.Input.Interop.0.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Microsoft::UI::Input::Interop
{
    struct WINRT_IMPL_EMPTY_BASES IPenDeviceInteropStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPenDeviceInteropStatics>
    {
        IPenDeviceInteropStatics(std::nullptr_t = nullptr) noexcept {}
        IPenDeviceInteropStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
