// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Windows_Devices_Pwm_Provider_2_H
#define WINRT_Windows_Devices_Pwm_Provider_2_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Windows.Devices.Pwm.Provider.1.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Windows::Devices::Pwm::Provider
{
}
#endif
