// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Microsoft_Windows_AI_Speech_1_H
#define WINRT_Microsoft_Windows_AI_Speech_1_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Microsoft.Windows.AI.Speech.0.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Microsoft::Windows::AI::Speech
{
    struct WINRT_IMPL_EMPTY_BASES IAudioConfiguration :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAudioConfiguration>
    {
        IAudioConfiguration(std::nullptr_t = nullptr) noexcept {}
        IAudioConfiguration(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IAudioConfigurationStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAudioConfigurationStatics>
    {
        IAudioConfigurationStatics(std::nullptr_t = nullptr) noexcept {}
        IAudioConfigurationStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IBatchRecognition :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBatchRecognition>
    {
        IBatchRecognition(std::nullptr_t = nullptr) noexcept {}
        IBatchRecognition(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IBatchRecognitionFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBatchRecognitionFactory>
    {
        IBatchRecognitionFactory(std::nullptr_t = nullptr) noexcept {}
        IBatchRecognitionFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISpeechAudioProvider :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISpeechAudioProvider>
    {
        ISpeechAudioProvider(std::nullptr_t = nullptr) noexcept {}
        ISpeechAudioProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISpeechRecognitionModel :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISpeechRecognitionModel>
    {
        ISpeechRecognitionModel(std::nullptr_t = nullptr) noexcept {}
        ISpeechRecognitionModel(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISpeechRecognitionModelResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISpeechRecognitionModelResult>
    {
        ISpeechRecognitionModelResult(std::nullptr_t = nullptr) noexcept {}
        ISpeechRecognitionModelResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISpeechRecognitionModelStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISpeechRecognitionModelStatics>
    {
        ISpeechRecognitionModelStatics(std::nullptr_t = nullptr) noexcept {}
        ISpeechRecognitionModelStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IStreamingRecognition :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IStreamingRecognition>
    {
        IStreamingRecognition(std::nullptr_t = nullptr) noexcept {}
        IStreamingRecognition(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IStreamingRecognitionFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IStreamingRecognitionFactory>
    {
        IStreamingRecognitionFactory(std::nullptr_t = nullptr) noexcept {}
        IStreamingRecognitionFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IStreamingRecognizedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IStreamingRecognizedEventArgs>
    {
        IStreamingRecognizedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IStreamingRecognizedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IStreamingRecognizingEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IStreamingRecognizingEventArgs>
    {
        IStreamingRecognizingEventArgs(std::nullptr_t = nullptr) noexcept {}
        IStreamingRecognizingEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
