// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Windows_Graphics_Printing_ProtectedPrint_1_H
#define WINRT_Windows_Graphics_Printing_ProtectedPrint_1_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Windows.Graphics.Printing.ProtectedPrint.0.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Windows::Graphics::Printing::ProtectedPrint
{
    struct WINRT_IMPL_EMPTY_BASES IWindowsProtectedPrintInfoStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsProtectedPrintInfoStatics>
    {
        IWindowsProtectedPrintInfoStatics(std::nullptr_t = nullptr) noexcept {}
        IWindowsProtectedPrintInfoStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
