// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Windows_System_Display_2_H
#define WINRT_Windows_System_Display_2_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Windows.System.Display.1.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Windows::System::Display
{
    struct WINRT_IMPL_EMPTY_BASES DisplayRequest : winrt::Windows::System::Display::IDisplayRequest
    {
        DisplayRequest(std::nullptr_t) noexcept {}
        DisplayRequest(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::System::Display::IDisplayRequest(ptr, take_ownership_from_abi) {}
        DisplayRequest();
    };
}
#endif
