// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Windows_Web_2_H
#define WINRT_Windows_Web_2_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Windows.Web.1.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Windows::Web
{
    struct WebError
    {
        WebError() = delete;
        static auto GetStatus(std::int32_t hresult);
    };
}
#endif
