// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_Microsoft_Windows_AI_Text_Experimental_1_H
#define WINRT_Microsoft_Windows_AI_Text_Experimental_1_H
#include "winrt/impl/Microsoft.Windows.AI.Text.Experimental.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Windows::AI::Text::Experimental
{
    struct WINRT_IMPL_EMPTY_BASES ILanguageModelExperimental :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILanguageModelExperimental>
    {
        ILanguageModelExperimental(std::nullptr_t = nullptr) noexcept {}
        ILanguageModelExperimental(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ILanguageModelExperimentalFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILanguageModelExperimentalFactory>
    {
        ILanguageModelExperimentalFactory(std::nullptr_t = nullptr) noexcept {}
        ILanguageModelExperimentalFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ILanguageModelOptionsExperimental :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILanguageModelOptionsExperimental>
    {
        ILanguageModelOptionsExperimental(std::nullptr_t = nullptr) noexcept {}
        ILanguageModelOptionsExperimental(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ILanguageModelOptionsExperimentalStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILanguageModelOptionsExperimentalStatics>
    {
        ILanguageModelOptionsExperimentalStatics(std::nullptr_t = nullptr) noexcept {}
        ILanguageModelOptionsExperimentalStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ILowRankAdaptation :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILowRankAdaptation>
    {
        ILowRankAdaptation(std::nullptr_t = nullptr) noexcept {}
        ILowRankAdaptation(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
