// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_Microsoft_Windows_Internal_ImageCreation_1_H
#define WINRT_Microsoft_Windows_Internal_ImageCreation_1_H
#include "winrt/impl/Microsoft.Windows.Internal.ImageCreation.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Windows::Internal::ImageCreation
{
    struct WINRT_IMPL_EMPTY_BASES IImageGeneratorSessionResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IImageGeneratorSessionResult>
    {
        IImageGeneratorSessionResult(std::nullptr_t = nullptr) noexcept {}
        IImageGeneratorSessionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
